### ISSUE TITLE
ERROR: for fauxpilot_triton_1  Cannot start service triton:

### ISSUE THREAD

**Issue by deven367** [moyix/fauxpilot#11]
Hello,

I was able to run `./setup.sh` successfully, upon trying to run `./launch.sh`, I get this error.

![image](https://user-images.githubusercontent.com/31466137/183238562-b9b3a7da-1326-4259-9fb2-bc289c01b590.png)

**Comment by moyix** [comment]
Hmm, this looks pretty similar to this issue from nvidia-docker:

https://github.com/NVIDIA/nvidia-docker/issues/1203

Can you try some of the steps there, like making sure you have the most recent NVIDIA drivers installed? Also, is this using Linux or are you using WSL on Windows? (WSL is not a configuration I've tried)

**Comment by deven367** [comment]
It's on wsl

**Comment by moyix** [comment]
Hmm, ok; I'd recommend going through NVIDIA's CUDA on WSL user guide and making sure that's all working first (if you haven't already):

https://docs.nvidia.com/cuda/wsl-user-guide/index.html

**Comment by deven367** [comment]
@moyix 
I think this a weird driver issue. When I try to train a model on WSL, I can see the model train on GPU but the GPU utilization still shows an error.

![image](https://user-images.githubusercontent.com/31466137/183296465-49ffc305-df60-48e6-8d24-f8633fc132c2.png)

I will close this issue over here. Thanks!

**Comment by moyix** [comment]
Ok! Hope you can get it working :)

**Comment by felipecrs** [comment]
BTW running FauxPilot in WSL2 is working fine for me.
