### ISSUE TITLE
[BUG] Always got empty result

### ISSUE THREAD

**Issue by jerryfangr** [moyix/fauxpilot#122]
# Env
> **Tip: Git clone at 2022.11.21**

 `.env`
```
MODEL=codegen-350M-multi
NUM_GPUS=1
MODEL_DIR=/h/Dev_space/fauxpilot/models/codegen-350M-multi-1gpu
API_EXTERNAL_PORT=15783
TRITON_HOST=triton
TRITON_PORT=18783
GPUS=0
```

# Log
**Cilent curl**
```bash
# Send request
curl -s -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"prompt":"def hello","max_tokens":100,"temperature":0.1,"stop":["\n\n"]}' http://localhost:15783/v1/engines/codegen/completions

# Get response
{"id": "cmpl-8gocbBH1T8AlOtFutlhzcrBjtRvMS", "choices": []}
```

**Server**
```bash
....................
2022-11-23 16:55:33 fauxpilot-triton-1         | W1123 21:13:22.751414 88 metrics.cc:426] Unable to get power limit for GPU 0. Status:Success, value:0.000000
2022-11-23 16:55:45 fauxpilot-copilot_proxy-1  | [StatusCode.UNAVAILABLE] failed to connect to all addresses
2022-11-23 16:55:45 fauxpilot-copilot_proxy-1  | Returned completion in 1.0101795196533203 ms
2022-11-23 16:55:45 fauxpilot-copilot_proxy-1  | INFO:     2022-11-23 21:18:17,093 :: 192.168.96.1:55540 - "POST /v1/engines/codegen/completions HTTP/1.1" 200 OK
```

**Server full log**
[log.zip](https://github.com/moyix/fauxpilot/files/10079258/log.zip)

# Other
I rollback some file to `2022.09.24 version`, then it work.
Here is the final project file: [fauxpilot-2022.09.24.zip](https://github.com/moyix/fauxpilot/files/10079461/fauxpilot-2022.09.24.zip)

**Comment by moyix** [comment]
I don't see anything obvious in the log files. I did just fix a bug related to an environment variable (https://github.com/moyix/fauxpilot/commit/e153c17194423cb4a010b858d5483052f6fe6bbb) so could you give a try with the most recent git version?

**Comment by jerryfangr** [comment]
> I don't see anything obvious in the log files. I did just fix a bug related to an environment variable ([e153c17](https://github.com/moyix/fauxpilot/commit/e153c17194423cb4a010b858d5483052f6fe6bbb)) so could you give a try with the most recent git version?

Good job, it's ok now.

i will close the issue.
