### ISSUE TITLE
API rate limit for fauxpilot?

### ISSUE THREAD

**Issue by smith-co** [moyix/fauxpilot#16]
Curious to know have you attempted to see how much load fauxpilot could handle? I know its  lot to do with the H/W that is provisioned.

Still would be curious to know what a typical GPU like RTX3090 or RTX A6000 could handle in terms of API request/minute?

**Comment by moyix** [comment]
It depends a lot on the output of the model unfortunately! The Copilot plugin typically makes requests for 500 tokens, which can take a long time for FauxPilot (~24.8 seconds in a quick test I did just now with a single A6000 and the 16B model). But most of these requests tell the model to stop generating when it emits a newline, so it doesn't end up generating anywhere near 500 tokens and the model finishes much faster. With the 16B model on an A6000 can expect it to take ~50ms per token generated.

Occasionally, like when you are at the start of a function, Copilot will make a request that tries to generate a longer chunk of code (by stopping on sequences like `\ndef ` or `\nif`), and that can be a bit slower (it's slower in the official Copilot as well).

If you have multiple GPUs you can generally expect the latency to decrease almost linearly (so two A6000s can generate almost twice as fast).

If you were trying to use this to serve many clients at once, you *might* be able to batch together multiple requests that come in at the same time, which would give you better throughput overall; I believe the underlying Triton inference server does support this.

In any case, improving inference latency is definitely something I'm interested in! But I think that will probably require looking at techniques like model compression and quantization.

**Comment by moyix** [comment]
Also, if you happen to put together something that tries to benchmark this with some real-world code using the kinds of requests Copilot makes I'd definitely be curious to see the results!

**Comment by nashid** [comment]
@moyix curious to know what happens if someone makes concurrent requests to `fauxpilot`. Those concurrent requests would be queued and would be served eventually? Or the concurrent requests would be lost?
