### ISSUE TITLE
Huggingface hub models 'moyix/codegen-16B-mono-gptj' - is this a direct port of codegen? 

### ISSUE THREAD

**Issue by cm2435** [moyix/fauxpilot#17]
Hi! Huge fan of project, really clean implementation, something I'd love to explore. 

I'm also working with the code-gen model set for some projects - is your huggingface model set the same base model (same trained weights*) that you've converted with faster transformer for optimized serving, or is this a different model set? 

Thanks so much in advance

**Comment by moyix** [comment]
Yes, the models are the same. I uploaded it to huggingface so that people wouldn't have to run the conversion themselves.
