### ISSUE TITLE
[ERROR] CUDA runtime error: the provided PTX was compiled with an unsupported toolchain.

### ISSUE THREAD

**Issue by fade-color** [moyix/fauxpilot#19]
I get the following error when I run `launch.sh`, how do I fix it? Thanks
```
fauxpilot-triton-1         | [FT][WARNING] Custom All Reduce only supports 8 Ranks currently. Using NCCL as Comm.
fauxpilot-triton-1         | I0811 02:59:27.879335 94 libfastertransformer.cc:307] Before Loading Model:
fauxpilot-triton-1         | terminate called after throwing an instance of 'std::runtime_error'
fauxpilot-triton-1         |   what():  [FT][ERROR] CUDA runtime error: the provided PTX was compiled with an unsupported toolchain. /workspace/build/fastertransformer_backend/build/_deps/repo-ft-src/src/fastertransformer/utils/cuda_utils.h:393
```

**Comment by neoinmatrix** [comment]
me too, how to solve

**Comment by moyix** [comment]
Which GPU are you using?

**Comment by neoinmatrix** [comment]
NVIDIA GeForce RTX 3060
NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4

**Comment by fade-color** [comment]
> me too, how to solve

I tried to upgrade cuda to 11.7 which solved the problem

**Comment by moyix** [comment]
Great – @neoinmatrix, does that work for you?

**Comment by neoinmatrix** [comment]
no ,  the cuda upgraded to 11.7 ,but the driver 470 is not supported, I try to upgraded the driver to 515, but driver not work. should i build the docker image by 11.4 cuda to run ?

**Comment by leemgs** [comment]
> CUDA runtime error: the provided PTX was compiled with an unsuppo

According to the "the provided PTX was compiled with an unsupported toolchain..." message, It seems that you have to up-to-date CUDA version to avoid the toolchain-related problem like this issue

**Comment by cxwx** [comment]
same issuse. can any one help to solve the problem with nvidia-driver-470?
cuda 11.7 is too new for stable version.
And the lastest stable version for debian is nvidia-driver-470 only support like cuda-11.2
