### ISSUE TITLE
No License, no fun

### ISSUE THREAD

**Issue by rurban** [moyix/fauxpilot#2]

**Comment by TechnologyClassroom** [comment]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by moyix** [comment]
Fixed in 695d77c27ead7eefa71c3ec2c954b59ef2eeb1a6, thanks!

**Comment by xloem** [comment]
I want to add my support for a GPL family license to encourage users to contribute chsnges back to the community. I believe this would help the project grow, and help new users discover and use future technological advances.
