### ISSUE TITLE
400 Bad Request when file has around 100 lines of code

### ISSUE THREAD

**Issue by richjohnson-wwt** [moyix/fauxpilot#215]
Is there a way to configure the max lines/tokens or other configuration to fix the 400 I am getting on medium size files?  I have increased the max lines and max tokens in the extension settings to 500 and 1000 respectively but that did not work.  This happens with different model choices.

# Issue Description
When the source file or java unit test file grows to 120 lines or so of code, my **200 OK** become **400 Bad Request**

`fauxpilot-copilot_proxy-1  | INFO:     2023-06-13 19:50:41,149 :: 172.29.198.78:55171 - "POST /v1/engines/codegen/completions HTTP/1.1" 200 OK
fauxpilot-copilot_proxy-1  | 1
fauxpilot-copilot_proxy-1  | INFO:     2023-06-13 19:51:02,653 :: 172.29.198.78:55176 - "POST /v1/engines/codegen/completions HTTP/1.1" 400 Bad Request`

Expected Result
============
200 Ok with response

How to Reproduce
===============
1. When src or test file grows to 150 lines
2. See error: "POST /v1/engines/codegen/completions HTTP/1.1" 400 Bad Request

**Comment by richjohnson-wwt** [comment]
Sorry, wrong repo.

**Comment by sveinnpalsson** [comment]
I have the same issue, did you solve it? @richjohnson-wwt

**Comment by richjohnson-wwt** [comment]
I believe the solution for us was in the fauxpilot vscode extension settings. We lowered the max_tokens and max_lines to around 150.
