### ISSUE TITLE
C# support!

### ISSUE THREAD

**Issue by Suriman** [moyix/fauxpilot#216]
Will Fauxpilot supports C#?

**Comment by Aincvy** [comment]
For now, it supports,  a little ...

![GIF 2023-8-23 10-53-32](https://github.com/fauxpilot/fauxpilot/assets/8110347/61d937d4-e95b-4dbb-a884-3a3816c92695)

**Comment by fdegier** [comment]
It depends on the model used, by default C# is not supported https://huggingface.co/Salesforce/codegen-2B-multi but you can choose a model that does support it.
