### ISSUE TITLE
Triton doesnt exist anymore I think?

### ISSUE THREAD

**Issue by IdotMaster1** [moyix/fauxpilot#223]
The docker image for triton (moyix/triton_with_ft) seems to be gone, deleted. How can we use the app now?

**Comment by marcotessarotto** [comment]
looks like the docker image exist, does this help?

https://hub.docker.com/r/moyix/triton_with_ft

**Comment by moyix** [comment]
The docker image seems fine -- maybe you can post the error message you're getting?

**Comment by IdotMaster1** [comment]
fuck.
