### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Docile1115** [moyix/fauxpilot#234]
I am using frogpilot.
I have a Lexus ES300, a Japanese car with right-hand drive, and I recently purchased a C3.

I installed it using the frogpilot URL, but the car is not being recognized.

It only displays the message "dashcam mode car unrecognized."

Can you help me with this?

**Comment by MamfTheKramf** [comment]
Hi,
looks like you're on the wrong repository. I think you're looking for this one: https://github.com/FrogAi/FrogPilot
