### ISSUE TITLE
What is the comparison of these model in huggingface?

### ISSUE THREAD

**Issue by bonuschild** [moyix/fauxpilot#235]
I've downloaded 350M & 2B model and both running well on my NVIDIA 3060 GPU. However, what is the exactly difference of these model? I just see the size and response time, but still don't know it very well.

Is there a typical performance of these model? such as responsing time, text length and so on. In the past I just think the 2B model is better than 350M model but I found it can not perform a "real-time" feeling when I use VSCode Plugins.

Thanks for every geekers' attention.

**Comment by bonuschild** [comment]
@moyix Would you mind helping me with this confusion? Thanks.

**Comment by fdegier** [comment]
The difference between the 350M and 2B models in Fauxpilot refers to the size and complexity of the underlying language model used for text generation tasks. The "M" and "B" stand for million and billion parameters, respectively, indicating the scale of the model.

The 2B model is significantly larger than the 350M model in terms of the number of parameters it contains. This typically results in a more comprehensive understanding of language nuances and contexts, allowing for potentially more accurate and contextually relevant text generation.
