### ISSUE TITLE
Company Proxy

### ISSUE THREAD

**Issue by csreekrishna** [moyix/fauxpilot#241]
I am very new to VSCode extensions and am working in a company that has proxy for the domain. I am not able to load the plugin in my VSCode environment. I copied extensions/vscode folder into extensions folder in VSCode extension area. Can someone help me why the plugin wouldn't load? Could it be because of my company proxy?

**Comment by fdegier** [comment]
Which extension do you mean? Fauxpilot relies on you using and installing the Copilot plugin, then configuring it to use your own hosted version of FauxPilot.
