### ISSUE TITLE
Dockerfile to build the moyix/triton_with_ft:22.06 image

### ISSUE THREAD

**Issue by akkashk** [moyix/fauxpilot#27]
The repository contains Dockerfiles to recreate the `moyix/model_converter:latest` and `moyix/copilot_proxy:latest` image but not the `moyix/triton_with_ft:22.06` image. Would it be possible to add the Dockerfile + config to build this image?

**Comment by moyix** [comment]
That can be found here:

https://github.com/moyix/fastertransformer_backend

I will try to make that more visible!

**Comment by moyix** [comment]
Closing this for now but tagging it so it can go into a FAQ / Documentation update.
