### ISSUE TITLE
Code Block suggestion

### ISSUE THREAD

**Issue by LukyBruce** [moyix/fauxpilot#40]
In fauxpilot, can we suggest full code block like github copilot? right now even I wrote a quick sort method, I need to tab 100 times.

**Comment by LukyBruce** [comment]
It looks like change max tokens will partially solve this issue, but when I change it to 100 tokens, vs code always fail to respond, and my GPU (3090) fan will go crazy.

**Comment by gongel** [comment]
你好，这个使用上有兴趣交流一下吗？vx: higongel

**Comment by linonetwo** [comment]
So this needs GPU to run? I thought I can run it with MacBook's CPU and start the server with a single docker run command...
