### ISSUE TITLE
Does this only support NVIDIA GPU's

### ISSUE THREAD

**Issue by Otrex** [moyix/fauxpilot#54]
Hi, I would like to know if the copilot only supports NVIDIA GPU's?

**Comment by TechnologyClassroom** [comment]
Yes, this repo is dependent on a fork of the NVIDIA Triton docker image which depends on NVIDIA hardware.

**Comment by Otrex** [comment]
Ok thanks

**Comment by TechnologyClassroom** [comment]
@Otrex Read https://github.com/moyix/fauxpilot/issues/4 for a method with CPU.
