### ISSUE TITLE
[Q] run on Android ?

### ISSUE THREAD

**Issue by azman0101** [moyix/fauxpilot#57]
Is there any chance that this project is able to run on android TV (Nvidia Shield Pro, which has a Tegra X1) ?

**Comment by Frederisk** [comment]
You mentioned Tegra X1 that is NVIDIA's chip, which I take to mean that you want to use CUDA on it.

First let's ignore annoying drivers, performance, etc. According to [this document](http://international.download.nvidia.com/pdf/tegra/Tegra-X1-whitepaper-v1.0.pdf), we can notice that this chip uses the Maxwell architecture（Compute Capability is 5.x). But the minimum Compute Capability required for this project is 6.0.

So I don't think it's a good idea, at least not yet.

**Comment by moyix** [comment]
Yep. Also, given the computational requirements of the model, running on the Tegra X1 would not be a very pleasant experience, I think.

**Comment by JBOClara** [comment]
Thanks for your answers @moyix @Frederisk 

And for your work (I've not tested yet because of GPU requirement).
It's amazing to see open-source project that ease the use of alternative to Github Copilot.
