### ISSUE TITLE
./launch.sh compile error: /mnt/c/Program no such file or directory

### ISSUE THREAD

**Issue by BoyuanJackChen** [moyix/fauxpilot#67]
I installed the requirements and installed choice 4 with 1 GPU in ./setup.sh. Then I called ./launch.sh with the following prints. I think the server was not launched. Simply creating a Program folder in my c drive didn't solve the problem. I wonder how to fix this? 

```
(base) boyuanchen@Owne:~/fauxpilot$ ls
LICENSE  README.md  config.env  converter  copilot_proxy  docker-compose.yaml  example.env  launch.sh  models  setup.sh

(base) boyuanchen@Owne:~/fauxpilot$ ./launch.sh
./launch.sh: line 19: /mnt/c/Program: No such file or directory

(base) boyuanchen@Owne:~/fauxpilot$ ./launch.sh
./launch.sh: line 19: /mnt/c/Program: Is a directory

(base) boyuanchen@Owne:~/fauxpilot$
```

**Comment by moyix** [comment]
Ah, yep, looks like `launch.sh` doesn't take into account the possibility that the path to `docker` may have a space in it, whoops. I'll make a patch fixing that but in the meantime if you change the last line of `launch.sh` from 
```
$DOCKER_COMPOSE up
```
to
```
"$DOCKER_COMPOSE" up
```

It should work.
