### ISSUE TITLE
Proposal: Participating in HactoberFest (10/1 - 10/31)

### ISSUE THREAD

**Issue by leemgs** [moyix/fauxpilot#78]
This year, HactoberFest will be held in October for one month.
Many GitHub open source projects are participating.

To encourage code contribution, I would like to suggest that this community participate here. 😺 
Methods for participation can be found in the ISSUE and Pull Request  (PR) menu.
@moyix , You may include the two labels such as **HACKTOBERFEST**, **HACKTOBERFEST-ACCEPTED**.

* https://hacktoberfest.com/
* https://github.com/topics/hacktoberfest
* https://dev.to/github/how-to-get-ready-for-hacktoberfest-2022-2ck2
```
Hacktoberfest is a month-long celebration of open source projects, their maintainers, 
and the entire community of contributors. Each October, open source maintainers 
give new contributors extra attention as they guide developers through their first 
pull requests on GitHub.
```

**Comment by leemgs** [comment]
FYI, Now, I got the Level3 among the Level 1 ~ 4.  It's funny to developers all over the world every year. :)

![image](https://user-images.githubusercontent.com/82404/195237051-21e5c368-9951-4489-bae0-24a700be795f.png)
![image](https://user-images.githubusercontent.com/82404/195237070-1fabc3da-dd83-4280-9d8b-1dd6016f3695.png)
![image](https://user-images.githubusercontent.com/82404/195237084-f5082868-a27d-45b3-a0eb-cf941d5c4d8f.png)

**Comment by moyix** [comment]
Hi – I'm willing, but unfortunately this month is very busy for me with a lot of travel. I'll do the best I can :)
