### ISSUE TITLE
Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]

### ISSUE THREAD

**Issue by rojnwa** [moyix/fauxpilot#9]
Hey,

installation went fine, no problems whatsoever. However, when trying to run `launch.sh` I get following error: 
```
➜ ./launch.sh       
[+] Running 1/0
 ⠿ Container fauxpilot-copilot_proxy-1  Running
Attaching to fauxpilot-copilot_proxy-1, fauxpilot-triton-1
Error response from daemon: could not select device driver "nvidia" with capabilities: [[gpu]]
```

I have all dependencies installed:

- docker (v. 20.10.17, build 100c70180f)
- docker-compose (v. 2.6.1)
- nvidia driver (v. 515.57, CUDA v. 11.7)
- nvidia-docker (v. 2.11.0-1)

Running on Arch Linux, kernel: 5.15.55-1-lts

**Comment by moyix** [comment]
Looks like the same issue as this: https://github.com/NVIDIA/nvidia-docker/issues/1034

Could you try the steps mentioned there?

**Comment by rojnwa** [comment]
> Looks like the same issue as this: [NVIDIA/nvidia-docker#1034](https://github.com/NVIDIA/nvidia-docker/issues/1034)
> 
> Could you try the steps mentioned there?

Awesome it worked, thanks.
